### ISSUE TITLE
Request new feature 

### ISSUE THREAD

**Issue by baoduy** [streamich/react-universal-interface#13]
Hi, this is really nice interface for React component development. However, I would like to request a new feature allow to pass a props to HOC. 

Example: 
```javascript
const child = withData(props)(MyChid);
```

**Comment by streamich** [comment]
You can do now

```js
const child = withData(MyChild, 'data', props);
```

Or you could do

```js
const withData2 = props => MyChild => withData(MyChild, 'data', props);
const child = withData2(props)(MyChid);
```

**Comment by baoduy** [comment]
I have tried but it is not working. I want to pass the props to WithData component insted of to MyChild component.
